import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import Footer from '@/components/layouts/Footer';
// Dans ton fichier _app.tsx ou _app.js
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import Header from '@/components/layouts/header';
import { auth } from '@/auth';
import { SessionProvider } from 'next-auth/react';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang='en'>
      <body className={montserrat.className}>
        <SessionProvider session={session}>
          <Header />
          <main className='flex min-h-screen flex-col text-gray-900'>
            {children}
          </main>
        </SessionProvider>
        <Footer />
      </body>
    </html>
  );
}
